# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d177fb18563ee4e6087267065ee5ed17a7203247889397426846032ad39f436e79a40883f705e17b5dd985f5e7970329fd90bf070a4d5aca94e86207d08a230

test:
  secret_key_base: 9f7f60e51a04c4e2deb7278e42ff83b44528a9f763fd0c7537d8222823ba76f34fd0dfcca2015049e1a3f2fdcadc91bfcc31b2e8405a233b5f9c30ad29b3ec5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
